### ISSUE TITLE
GUI Text has unclear requirement

### ISSUE THREAD

**Issue by fullreboot** [EasyAbp/AbpHelper.GUI#100]
For Code Generation there are two sections (CRUD and Migrations) that require specifying the project for Migrations. The label for the text input is "Migration Project Name" when it's really looking for the "Migration Project Filename." It is not apparent from the label text or the documentation that it's looking for the full filename of the project. 

https://github.com/EasyAbp/AbpHelper.GUI/search?q=Migration+project+name

Doing a quick search for that string reveals that it's the name of both the Variable and the localized resource text. 

Suggestions for now would be (in no particular order)

- change the localized string to say "Migration Project Filename"
- Use placeholder text to give a contextual clue `EntityFrameworkCore.csproj`
- Include a dropdown to select the project from a list

![image](https://user-images.githubusercontent.com/90530881/142780931-59b60d72-1861-4b6c-8702-92036026cda5.png)

**Comment by fullreboot** [comment]
https://github.com/EasyAbp/AbpHelper.GUI/issues/99

**Comment by fullreboot** [comment]
Actually I see there's some action being taken to bring this functionality into a different direction.

https://github.com/EasyAbp/AbpHelper.GUI/issues/27

**Comment by gdlcf88** [comment]
A placeholder text is a good tip. I can not change the word "name" to "filename" since the "Migration project name" is from AbpHelper CLI.

#27 is fixing the problem for only module host projects and unfortunate I don't have time to finish it recently.

Thanks @fullreboot, no matter what you are willing to improve, welcome to PR.

**Comment by gdlcf88** [comment]
![image](https://user-images.githubusercontent.com/30018771/168300205-ef7f97bd-6ec5-4a52-8641-c95379a6de2a.png)

I create some alerts to help people find documents or related source codes.
