### ISSUE TITLE
GUI not work on mac catalina

### ISSUE THREAD

**Issue by KaungZawHtet** [EasyAbp/AbpHelper.GUI#101]
<img width="415" alt="Screen Shot 2021-11-28 at 09 43 38" src="https://user-images.githubusercontent.com/15225530/143727414-2acdba81-b214-4ea9-b98a-5e2e9d1e9cf6.png">

**Comment by gdlcf88** [comment]
See https://github.com/EasyAbp/AbpHelper.GUI/issues/55
