### ISSUE TITLE
not working with mongodb

### ISSUE THREAD

**Issue by atak946** [EasyAbp/AbpHelper.GUI#107]
Hi,

gui helper code generator not working with mongodb, 

System.IO.FileNotFoundException: AccountingDbContext.cs, application doesn't continue generate code files after this error

Is there a solution for this problem?

I downloaded the source code, but the core code is not interfered with.

**Comment by gdlcf88** [comment]
https://github.com/EasyAbp/AbpHelper.CLI/issues/170
