### ISSUE TITLE
[建议]生成cs页面编码为utf-8

### ISSUE THREAD

**Issue by liaozb** [EasyAbp/AbpHelper.GUI#108]
![image](https://user-images.githubusercontent.com/12622501/168012145-5e4d174f-438d-4df5-b9f5-020d049f31a6.png)
现在是gb2312格式

**Comment by gdlcf88** [comment]
Sure we need UTF-8. Can you create a PR to fix it?

**Comment by wakuflair** [comment]
The generated code is ASCII only, so it's displayed as your default encoding.
