### ISSUE TITLE
Code Gernerator will throw exception when building in a module project without ui 

### ISSUE THREAD

**Issue by yuzhigang** [EasyAbp/AbpHelper.GUI#11]
while buiding a module project in cli  as follows:
abp new MyModule -t module --no-ui

VS project will not include  *.Unifed.Web.csproject. 
AbpHelper.Cli throw an exception: ' System.NotSupportedException: Unknown ABP project structure.'

**Comment by gdlcf88** [comment]
Maybe we should check the existence of `MyModule.Host.Shared` project instead of checking the exsitence of `MyModule.Web.Unified`.

What do you think? @wakuflair

**Comment by gdlcf88** [comment]
Moved to https://github.com/EasyAbp/AbpHelper.CLI/issues/52
