### ISSUE TITLE
Very nice, are you able to select a version

### ISSUE THREAD

**Issue by papyr** [EasyAbp/AbpHelper.GUI#12]
Hello, this is fantastic, are we able to select any version of ABP or only latest version.

thanks

**Comment by gdlcf88** [comment]
AbpHelper code generator does not check the ABP version of your solution, it just generate code.

Generally, the code adapts to all versions. If latest ABP version brings a breaking change, the next AbpHelper CLI will be updated to adapt it, but you can still keep older AbpHelper CLI version, see:

![image](https://user-images.githubusercontent.com/30018771/79713409-4e975280-8300-11ea-9fcb-d55ef3eaf8ac.png)

**Comment by papyr** [comment]
awesome!!!
