### ISSUE TITLE
从web生成个项目，GUI为0.24版生成代码出错

### ISSUE THREAD

**Issue by cicna** [EasyAbp/AbpHelper.GUI#13]
如图所示：
![abp01](https://user-images.githubusercontent.com/18661156/81503070-3bcad900-9314-11ea-964b-01722e437f95.png)

![abp02](https://user-images.githubusercontent.com/18661156/81503091-53a25d00-9314-11ea-9f69-18b10c92bcad.png)

**Comment by gdlcf88** [comment]
Try to use AbpHelper CLI directly to reproduce your problem.

**Comment by wakuflair** [comment]
I guess it's because you don't install ef tools, use following command to install and retry:
`dotnet tool install -g dotnet-ef`
