### ISSUE TITLE
Missing necessary "using" after generating razor page

### ISSUE THREAD

**Issue by motl2000** [EasyAbp/AbpHelper.GUI#14]
ABP framework V2.9
Following the Bookstore demo on the ABP docs, there are errors after generating the razor page.
For example, in the CreateModal.cshtml. 

@page
@using AbpHelp4.Localization
@inject **IHtmlLocalizer**<AbpHelp4Resource> L
@model AbpHelp4.Web.Pages.AbpHelp4.Book.CreateModalModel
@{
    Layout = null;
}
<abp-dynamic-form abp-model="ViewModel" data-ajaxForm="true" asp-page="CreateModal">
    <abp-modal>
        <abp-modal-header title="@L["CreateBook"].Value"></abp-modal-header>
        <abp-modal-body>
            <abp-form-content />
        </abp-modal-body>
        <abp-modal-footer buttons="@(**AbpModalButtons**.Cancel|**AbpModalButtons**.Save)"></abp-modal-footer>
    </abp-modal>
</abp-dynamic-form>

1. The "IHtmlLocalizer" will not be recognized because missing reference.
2. AbpModalButtons also need reference.

2 reference need to be added.
@using Microsoft.AspNetCore.Mvc.Localization
@using Volo.Abp.AspNetCore.Mvc.UI.Bootstrap.TagHelpers.Modal;

**Comment by gdlcf88** [comment]
This is about [AbpHelperCLI](https://github.com/EasyAbp/AbpHelper.CLI). @wakuflair 

The "using" has been removed in the commit:
https://github.com/EasyAbp/AbpHelper.CLI/commit/71f02288545c185d2a21af62ce36b2b16fc41a23

**Comment by motl2000** [comment]
OK, but it causes debug error after generate code. Do I miss something?

**Comment by wakuflair** [comment]
Hi @motl2000 
Thank you for this issue, CLI has this bug indeed.
It's been fixed by https://github.com/EasyAbp/AbpHelper.CLI/commit/bfc4f4ff4a0d51b347cb1c8956c8ca2bb027f32d

@gdlcf88 
The "using" statements are removed by Rider when commit. 
Because I checked on the "Optimize improts" option, which should be very careful when you have generation work.
