### ISSUE TITLE
MacOS13.1 ERROR

### ISSUE THREAD

**Issue by haoyk** [EasyAbp/AbpHelper.GUI#146]
macOS13.1 
m1 MacBook Pro 
node v16.17.0

<img width="544" alt="image" src="https://user-images.githubusercontent.com/10443647/212818701-1a0edd6d-9fbe-418e-9c63-fb29d6cf9f8a.png">

**Comment by gdlcf88** [comment]
I believe v2.5.2 fixed the problem.

https://github.com/EasyAbp/AbpHelper.GUI/releases/tag/v2.5.2

BTW, I made the CI/CD provides a .dmg file for ARM64. However, the file is always broken, so I had to build it myself and override the [AbpHelper-2.5.2-arm64.dmg](https://github.com/EasyAbp/AbpHelper.GUI/releases/download/v2.5.2/AbpHelper-2.5.2-arm64.dmg) file on the release. Best if you could try this ARM64 version.

**Comment by haoyk** [comment]
Thank you for fixing the bug, it is working well.
