### ISSUE TITLE
CRUD add a option to skip entity configuration

### ISSUE THREAD

**Issue by holyrong** [EasyAbp/AbpHelper.GUI#157]
Why not add a checkbox to skip entity configuration items?
I don't need the following code snippet when generate crud code:

`builder.Entity<Member>(b =>  {
            b.ToTable(MembersConsts.DbTablePrefix + "Member", MembersConsts.DbSchema);
            b.ConfigureByConvention(); 
        });`

**Comment by wakuflair** [comment]
I think these code are necessary for almost all other users.
You can delete them manually after generation.

**Comment by holyrong** [comment]
> I think these code are necessary for almost all other users. You can delete them manually after generation.

![image](https://user-images.githubusercontent.com/8318475/232359250-08664f12-ab7f-4730-9c1a-b79b8097d6d3.png)
增加一个这样的选项，不是更方便吗？很多情况都是先配置好实体了，再编写服务的。不可能一个表一个表的去执行DBMigration。而且大部分情况，我们也不可能把所有的配置信息写到一个类里，这会导致DBContext变成一个巨无霸的类了。

**Comment by holyrong** [comment]
@gdlcf88 这个问题没修复啊，为啥关闭了？
