### ISSUE TITLE
No layer application can not generate the code

### ISSUE THREAD

**Issue by xinjiboy1234** [EasyAbp/AbpHelper.GUI#176]
i can create the no layer project with AbpHelper.GUI ,  but i can not generate any code,  i tried CRUD, and application service with AbpHelper.GUI and no layer project, but it not works.
is it not supported or there has other specify operation process?

**Comment by gdlcf88** [comment]
We did not test for the `app-nolayers` template.

**Comment by xinjiboy1234** [comment]
really thanks for you do so much for open source community , but I'd also like to ask you, do you plan to support tierless projects?

**Comment by gdlcf88** [comment]
No plan for now. EasyAbp is open-sourced so you are welcome to contribute if you want.
