### ISSUE TITLE
Run Gennrate CRUD Error

### ISSUE THREAD

**Issue by lovelycoco** [EasyAbp/AbpHelper.GUI#25]
![image](https://user-images.githubusercontent.com/25974343/92221301-d953a500-eecf-11ea-9c3c-f8845e69b527.png)

Error while invoking activity activity-6 of workflow .How to solve the problem?

**Comment by wakuflair** [comment]
Does the entity file `Book.cs` exist?

**Comment by lovelycoco** [comment]
No entity file was generated.

**Comment by lovelycoco** [comment]
> Does the entity file `Book.cs` exist?

No entity file was generated.
I used Windows 7.

**Comment by wakuflair** [comment]
The entity file is required to use the crud feature.
You need define it first.

**Comment by lovelycoco** [comment]
> The entity file is required to use the crud feature.
> You need define it manually first.

OK，Thank you！
