### ISSUE TITLE
Master Detail Page

### ISSUE THREAD

**Issue by papyr** [EasyAbp/AbpHelper.GUI#31]
Hello, very nice can you please add Master Detail Controller and Views

**Comment by wakuflair** [comment]
Hi
I noticed that the latest ASP.NET Zero v9.2 RAD tool has implemented this feature. 
I will see how it works and add this feature in future.

**Comment by papyr** [comment]
Great thanks!!!

**Comment by weedkiller** [comment]
Hello, I am interested in the Master Detail as well, can you share some help please
