### ISSUE TITLE
Can't run command when the USERPROFILE variable has space

### ISSUE THREAD

**Issue by tungchau** [EasyAbp/AbpHelper.GUI#35]
Commands such as `%USERPROFILE%\.dotnet\tools\abphelper module add` causes error in case of the USERPROFILE variable has space(s)

**Comment by gdlcf88** [comment]
Hi @tungchau,

This is really a problem.

Normally, warping the path can fix it:
`"%USERPROFILE%"\.dotnet\tools\abphelper module add`
or
`"%USERPROFILE%\.dotnet\tools\abphelper module add"`
but when I use it in the child_process.exec that the GUI app depends on, it throws: "The filename, directory name, or volume label syntax is incorrect."

I don't know how to solve it yet, do you have any idea?

**Comment by tungchau** [comment]
Using just `abphelper module add...` works for me, since `%USERPROFILE%\.dotnet\tools` has been already in my PATH.

**Comment by gdlcf88** [comment]
Removing the prefix `%USERPROFILE%\.dotnet\tools\` causes other problems.

**Comment by gdlcf88** [comment]
I am closing this issue since the v1.0.0 AbpHelper GUI based on Blazor was released.
