### ISSUE TITLE
Is it possible to use abphelper with asp.net 5 abp project

### ISSUE THREAD

**Issue by jmglezgz** [EasyAbp/AbpHelper.GUI#36]
Morning guys,
  Thanks so much for this great community!. I was wondering if it's possible to generate crud operations with abphelper using a [asp.net 5 abp project structure](https://github.com/abpframework/abp/releases/tag/4.0.0-rc.3).

Appreciated you answers,
Jose

**Comment by gdlcf88** [comment]
Thanks for your concern.

AbpHelper GUI/CLI is not ready for ABP 4.0+ since the latter is still the RC version.

Please watch this repository and you will be informed when the latest ABP version is supported.

**Comment by wakuflair** [comment]
I think you mean ABP 4.0, right?

As ABP 4.0 final is released, ABPHelper will support it.
For now, ABPHelper supports ABP 3.3.0.

**Comment by jmglezgz** [comment]
Hi guys, do you know if ABP Helper already supports ABP 4.x? 
Thanks,
