### ISSUE TITLE
版本和模板

### ISSUE THREAD

**Issue by gzh4455** [EasyAbp/AbpHelper.GUI#42]
这个工具能不能内置vnext 的各个版本的？不用从abp 的网站的下载？ 
否则这个vnext 发布新版本后， 后面就不能获取老版本的。

还有那个模块的功能怎么用？

**Comment by wakuflair** [comment]
> 否则这个vnext 发布新版本后， 后面就不能获取老版本的。

可以使用Version参数指定要使用的版本.

> 还有那个模块的功能怎么用？

你说的是Install community modules功能吧? 可以安装社区模块, 
各个选项GUI上有详细的描述.

**Comment by gzh4455** [comment]
你好，

首先感谢你的回复！

最在使用Vnext , 感觉有这个框架还是比较好，当然看源码也遇到一些问题，希望可以多多请教。

回到之前的问题，不是moudle 的问题，是本身的vnext 的主流版本。

就是那个Vnext 下载的模块，如下面， 官网经常会出现问题。执行类似的abp new Acme.BookStore命令，模板经常会下载不下来 。 由于版本更新的问题，一旦更新到4.3， 4.1 的无法使用了。
[cid:image003.png@01D6EA69.14323A30]

另一个问题是template source 的问题，这个不是知道如何使用。

[cid:image004.png@01D6EA68.E4C89FA0]

请问可以加一个微信或者其他的沟通工具，一些开源的工具有空可以一起开发和探讨。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Yuhang Ji<mailto:notifications@github.com>
发送时间: 2021年1月14日 11:23
收件人: EasyAbp/AbpHelper.GUI<mailto:AbpHelper.GUI@noreply.github.com>
抄送: gzh4455<mailto:gzh4455@hotmail.com>; Author<mailto:author@noreply.github.com>
主题: Re: [EasyAbp/AbpHelper.GUI] 版本和模板 (#42)


否则这个vnext 发布新版本后， 后面就不能获取老版本的。

可以使用Version参数指定要使用的版本.

还有那个模块的功能怎么用？

你说的是Install community modules功能吧? 可以安装社区模块,
各个选项GUI上有详细的描述.

―

**Comment by wakuflair** [comment]
ABP的模板服务器现在在土耳其, 国内访问速度确实慢, 我也经常会有网络问题, 建议常备梯子.

可以加入EasyAbp的QQ群: 692022137
