### ISSUE TITLE
How to setup the page folder

### ISSUE THREAD

**Issue by ThreeLambs** [EasyAbp/AbpHelper.GUI#43]
1. I Create the class ``Holodays/Holiday.cs`` in Domain.
2. run the AbpHelper.GUI tool ``Generate CRUD``, but the page location in Web 
is ``Holodays/Holiday/Index.cshtml`` , Witch I hope is ``Holodays/Index.cshtml`` .
How to setup it.

**Comment by gdlcf88** [comment]
The result is expected since there may be other aggregate roots in the Holidays floder.

If you want to customize the floder structure, please do it yourself manually after generation.
