### ISSUE TITLE
Discussion on Abp Module Store design.

### ISSUE THREAD

**Issue by gdlcf88** [EasyAbp/AbpHelper.GUI#5]
1. Can GitHub be used as the server?
2. What if someone want to publish a paid module?
3. Can AbpHelper CLI be used to list, install, update and uninstall modules from the store?

**Comment by gdlcf88** [comment]
First, we need a modules installation helper sub command in AbpHelper CLI like:

`abphelper module install HelloModule.Domain D:\MyProject`
`abphelper module install HelloModule.Domain D:\MyProject --target MyProject.Domain`

Then the process can be:

1. EasyAbp team builds a registration form for community packages, each package may have many abp modules.

1. Developers find a package and choose the modules they need to install, AbpHelper CLI installs the modules one by one.

1. If possible, we generate the configuration code in the installation.

What do you think? @wakuflair

**Comment by wakuflair** [comment]
I think the ABP official team will do this job sooner or later😛

**Comment by gdlcf88** [comment]
Hello @hikalkan, could you please tell us if abp has any plans to develop a official module store?

**Comment by hikalkan** [comment]
Hi all,

Yes, market.abp.io is on the road map. We have designed it (and already answered the questions above). You will be able to add free & paid modules to the market. This was one of the main goals behind the ultimate modularity of the ABP framework :)

No release date yet, but we hope you'll not wait much :)

**Comment by gdlcf88** [comment]
Excellent! So we wait for the official market.
