### ISSUE TITLE
Not working on Windows 10

### ISSUE THREAD

**Issue by aelhadi** [EasyAbp/AbpHelper.GUI#51]
![image](https://user-images.githubusercontent.com/5918026/109413312-f8c61900-79ac-11eb-90d8-7681e8565547.png)

**Comment by gdlcf88** [comment]
Please check the logs in `C:\Users\elhad_49h70uh\AppData\Local\Programs\abphelper-gui\dotnet\EasyAbp.AbpHelper.Gui.HttpApi.Host\Logs`.

**Comment by aelhadi** [comment]
nothing in log just : 

2021-02-28 18:06:18.968 +01:00 [INF] Starting EasyAbp.AbpHelper.Gui.HttpApi.Host.

**Comment by gdlcf88** [comment]
What if you manually run the `EasyAbp.AbpHelper.Gui.HttpApi.Host` and the `EasyAbp.AbpHelper.Gui.Blazor.Host`?

**Comment by aelhadi** [comment]
![image](https://user-images.githubusercontent.com/5918026/109427154-52e8cd80-79f1-11eb-9dc9-40feb1848094.png)



![image](https://user-images.githubusercontent.com/5918026/109427163-61cf8000-79f1-11eb-879d-175512d0aa38.png)

**Comment by aelhadi** [comment]
![image](https://user-images.githubusercontent.com/5918026/109427234-b70b9180-79f1-11eb-9837-a1dfa4ce2ef7.png)

**Comment by gdlcf88** [comment]
Use `--urls` to specify a usable address.

**Comment by aelhadi** [comment]
ok but can't lunch it with https

![image](https://user-images.githubusercontent.com/5918026/109427350-53359880-79f2-11eb-9c1b-4857c31737f2.png)


![image](https://user-images.githubusercontent.com/5918026/109427366-69435900-79f2-11eb-882e-81645780290a.png)

**Comment by gdlcf88** [comment]
https://github.com/EasyAbp/AbpHelper.GUI/blob/master/electron/main.js#L27-L39

Port 44373 for EasyAbp.AbpHelper.Gui.HttpApi.Host.

Port 8005 for EasyAbp.AbpHelper.Gui.Blazor.Host.

**Comment by aelhadi** [comment]
![image](https://user-images.githubusercontent.com/5918026/109427561-44031a80-79f3-11eb-928e-5b0b28808112.png)

![image](https://user-images.githubusercontent.com/5918026/109427578-4e251900-79f3-11eb-8629-b27a2a442b4d.png)


![image](https://user-images.githubusercontent.com/5918026/109427606-61d07f80-79f3-11eb-949d-5b44b91ecebf.png)

**Comment by gdlcf88** [comment]
Thank you for your information. I will try to fix it.

**Comment by gdlcf88** [comment]
Hi @aelhadi.

I am not sure if this is the reason: https://docs.microsoft.com/en-us/dotnet/core/additional-tools/self-signed-certificates-guide#with-dotnet-dev-certs.

**Comment by aelhadi** [comment]
hello @gdlcf88 ,

i already have a certificat for localhost.
i'will clone your repo localy and try to invertigate...

![image](https://user-images.githubusercontent.com/5918026/109612017-6601b780-7b2f-11eb-8e6a-f006927b3920.png)

**Comment by aelhadi** [comment]
Hello @gdlcf88 ,

the solution is to run with --trust : 
```batch
dotnet dev-certs https --trust
```

Best Regards.

**Comment by gdlcf88** [comment]
Try to run `dotnet dev-certs https --trust` before the hosts start.

https://github.com/EasyAbp/AbpHelper.GUI/commit/2c2ca2992d42c1d2961231712ada83d7340713fc
