### ISSUE TITLE
Generate multiple/batch mass generator files at once and save configuration

### ISSUE THREAD

**Issue by weedkiller** [EasyAbp/AbpHelper.GUI#52]
Hello, is there a way to generate multiple files from database, or settings file.

**Comment by wakuflair** [comment]
Could you explain it with more details?

**Comment by weedkiller** [comment]
Many business applications have more than one entities/objects we want to use EasyABP like Customer, Product, Order, Profile, Widget, OrgUnit etc.  and we want to bulk generate whole batch of files, it would be very nice to quickly generate all those from one batch run.

**Comment by wakuflair** [comment]
For now we have no plan for implementing this, see https://github.com/EasyAbp/AbpHelper.CLI/pull/107.
