### ISSUE TITLE
打开了没有任何显示，怎么看报错。。

### ISSUE THREAD

**Issue by Qianzujin** [EasyAbp/AbpHelper.GUI#54]
![image](https://user-images.githubusercontent.com/49854479/109599053-82b0e600-7b55-11eb-8362-16c791b8b24e.png)

**Comment by 54czp** [comment]
同样的问题

**Comment by gdlcf88** [comment]
https://github.com/EasyAbp/AbpHelper.GUI/issues/51#issuecomment-789669737
