### ISSUE TITLE
Version 1.0 (Release, MacOS) is not working

### ISSUE THREAD

**Issue by tungchau** [EasyAbp/AbpHelper.GUI#55]
I took a quick install and got this error on Mac (BigSur)
![Screen Shot 2021-03-02 at 15 31 24](https://user-images.githubusercontent.com/4517250/109621272-56a15f00-7b6d-11eb-971d-ce2ff0b1af3b.png)

**Comment by gdlcf88** [comment]
Could you please pull the source code and try to debug it?

**Comment by dupeng0811** [comment]
遇到一样的问题，从Git pull下来在目录运行  `npm run package` ，出现错误。

![1](https://user-images.githubusercontent.com/14212481/111763334-fafd0280-88dc-11eb-9016-6a299b37df9e.jpg)


这个是log文件
[2021-03-19T09_57_03_396Z-debug.log](https://github.com/EasyAbp/AbpHelper.GUI/files/6170237/2021-03-19T09_57_03_396Z-debug.log)

**Comment by gdlcf88** [comment]
https://github.com/electron-userland/electron-builder/issues/5410

**Comment by dupeng0811** [comment]
> [electron-userland/electron-builder#5410](https://github.com/electron-userland/electron-builder/issues/5410)

谢谢，不过编译出来的.app文件，卸载之前的重新安装还是一样的报错...
![Snipaste_2021-03-22_13-59-20](https://user-images.githubusercontent.com/14212481/111946743-105d7100-8b17-11eb-9716-b8132c67951b.jpg)
![Snipaste_2021-03-22_13-59-12](https://user-images.githubusercontent.com/14212481/111946747-118e9e00-8b17-11eb-9db6-f247637dd7b1.jpg)

**Comment by HillCat** [comment]
The Same Problem ,But I used git cloned the source use vs code, don't know how to debug electron, don't know how to install the electron debug enviroment.

**Comment by JadynWong** [comment]
https://github.com/sindresorhus/fix-path/issues/16

Start successfully with `fix-path` version 3.0.0.

```js
npm install fix-path@v3.0.0
```
