### ISSUE TITLE
模块安装错误

### ISSUE THREAD

**Issue by 54czp** [EasyAbp/AbpHelper.GUI#56]
![image](https://user-images.githubusercontent.com/17570717/110073210-f3583c80-7db9-11eb-97e7-afc875ea5647.png)

**Comment by gdlcf88** [comment]
Please check the logs.------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;54czp&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年3月5日(星期五) 中午1:52
收件人:&nbsp;&quot;EasyAbp/AbpHelper.GUI&quot;<AbpHelper.GUI@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[EasyAbp/AbpHelper.GUI] 模块安装错误 (#56)

**Comment by gdlcf88** [comment]
Please check the logs.

![image](https://user-images.githubusercontent.com/30018771/110110660-21557500-7dea-11eb-8c61-2d701624bc3f.png)
