### ISSUE TITLE
module code generation Bug

### ISSUE THREAD

**Issue by xewn** [EasyAbp/AbpHelper.GUI#8]
![image](https://user-images.githubusercontent.com/1423410/76186605-d112f980-620d-11ea-83a4-4d7ec227e18b.png)
aspnet-core应该是应用的文件夹目录结构。
模块的目录结构应该是src
没法给模块生成代码。

**Comment by gdlcf88** [comment]
I don't have a good plan yet, maybe we should remove the folder check. For now, you can use AbpHelper CLI directly to generate codes for modules.

**Comment by gdlcf88** [comment]
Modules have been supported after version 0.2.1.
