### ISSUE TITLE
Wrong DBMS when creating new app.

### ISSUE THREAD

**Issue by dangminhbk** [EasyAbp/AbpHelper.GUI#85]
I select Mysql in the Database management system section, but the project was generated with SQL server one.
Here is the log

`  - EasyAbp.AbpHelper.Gui.AbpCli.New.AbpCliNewAppService.CreateAppAsync (5075 ms.)
    {"input":{"template":"app","ui":2,"separateIdentityServer":false,"tiered":false,"mobile":1,"databaseProvider":1,"solutionName":"Edu.ThreeDWeb","outputFolder":"C:\\PR01","version":"4.3.2","preview":false,"templateSource":null,"createSolutionFolder":true,"connectionString":null,"databaseManagementSystem":2,"localFrameworkRef":null,"noRandomPort":false}}
`

**Comment by dangminhbk** [comment]
@gdlcf88 thanks you, that super fast!

**Comment by gdlcf88** [comment]
It seems that the GitHub Action is broken, I need time to fix it.
