### ISSUE TITLE
mac book M1  error v1.3.2

### ISSUE THREAD

**Issue by OaimIsGnay** [EasyAbp/AbpHelper.GUI#88]
![image](https://user-images.githubusercontent.com/58240619/124004476-a0f6f780-da0a-11eb-901c-d0936a8b35a4.png)

**Comment by OaimIsGnay** [comment]
![image](https://user-images.githubusercontent.com/58240619/124004599-c126b680-da0a-11eb-9793-f731c9e038ae.png)

**Comment by gdlcf88** [comment]
See https://github.com/EasyAbp/AbpHelper.GUI/issues/55
