### ISSUE TITLE
使用 Code Generator 功能 报错

### ISSUE THREAD

**Issue by zhu6361420** [EasyAbp/AbpHelper.GUI#9]
%USERPROFILE%\.dotnet\tools\abphelper generate crud Contact -d E:\Demo\addressbook\addressbook --separate-dto --custom-repository --skip-db-migrations --skip-ui

Running...
'C:\Users\Administrator\.dotnet\tools\abphelper' is not recognized as an internal or external command,
operable program or batch file.

**Comment by gdlcf88** [comment]
![image](https://user-images.githubusercontent.com/30018771/77132257-b7897180-6a99-11ea-99ac-cbd2b3eb07bb.png)

Install the AbpHelper CLI first.
