### ISSUE TITLE
macOS error 

### ISSUE THREAD

**Issue by ktngoykalolo** [EasyAbp/AbpHelper.GUI#94]
cannot run on mac os due to security error , what can be done to resolve this ? 
![Screen Shot 2021-08-28 at 05 29 41](https://user-images.githubusercontent.com/3276588/131205888-8992449c-dc71-4fc8-84ff-ff521dbf0004.png)

**Comment by gdlcf88** [comment]
Could you please pull the source code and try to debug it?

```
cd electron
npm i
npm run dev
```
