### ISSUE TITLE
CRUD not generating anything

### ISSUE THREAD

**Issue by joe704la** [EasyAbp/AbpHelper.GUI#99]
I followed the instructions to create CRUD based on two different entities and it said it was completed within a second. But it didn't generate anything. I tried several times.

**Comment by Thiblosh** [comment]
I am also getting the same results.
On the actual entity gets updated by adding a parameterized constructor and a default empty protected one.

**Comment by gdlcf88** [comment]
please try to use the [AbpHelper CLI](https://github.com/EasyAbp/AbpHelper.CLI) directly and debug the generation steps.

**Comment by fullreboot** [comment]
@joe704la @Thiblosh 

Make sure your ABP Solution and your CLI have "matching" versions. I ran into this issue a few times
